import type { Metadata } from "next";
import "./globals.css";
import { NextAuthProvider } from "@/components/auth/providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja" suppressHydrationWarning>
			<body className="flex min-h-svh flex-col" suppressHydrationWarning>
				<main className="flex flex-1 flex-col">{children}</main>
			</body>
		</html>
	);
}
